blog/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
# from entries import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^change_blog/', views.SelectBlogView.as_view())
]

blog/entries/models.py
from __future__ import unicode_literals

from django.db import models

COUNTRY_CHOICES = (
    ('ar', 'Argentina'),
    ('us', 'United States'),
    ('de', 'Germany'),
    ('br', 'Brazil'),
    ('fr', 'France')
)


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __unicode__(self):
        return self.name

    __str__ = __unicode__


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    nationality = models.CharField(max_length=2, choices=COUNTRY_CHOICES)

    def __unicode__(self):
        return self.name

    __str__ = __unicode__


class Entry(models.Model):
    blog = models.ForeignKey(Blog)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField(auto_now_add=True)
    mod_date = models.DateField(auto_now=True)
    authors = models.ManyToManyField(Author)
    number_comments = models.IntegerField()
    scoring = models.DecimalField(max_digits=3, decimal_places=2)

    def __unicode__(self):
        return self.headline

    __str__ = __unicode__

blog/entries/forms.py
from django import forms

from entries.models import Blog


class SelectBlogForm(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)
    blog = forms.ModelChoiceField(Blog.objects)

blog/entries/views.py
from django.shortcuts import render

# Create your views here.

blog/entries/templates/entries/admin/change_blog.html
{% extends 'admin/base_site.html' %}

{% block content %}

  <form id="change_blog_form" method="POST">
    {% csrf_token %}
    <p>Change entries' blog to:</p>
    {{ form.as_p }}
    <input type="hidden" name="action" value="change_blog"/>
    <input type="submit" name="apply" value="Apply"/>
  </form>

{% endblock %}

blog/entries/templates/entries/admin/statistics.html
{% extends 'admin/base_site.html' %}

{% block content %}

  <p>Number of blogs: {{ blogs.count }}</p>
  {% for blog in blogs %}
    <p>{{ blog.name }}: {{ blog.entry_set.count }} entries</p>
  {% endfor %}

{% endblock %}